/**
 * recipes events
 */
export default {
  GET_ALL_PAGES: 'GET_ALL_PAGES',
  GET_ALL_PAGES_SUCCESS: 'GET_ALL_PAGES_SUCCESS',
  GET_ALL_PAGES_FAILURE: 'GET_ALL_PAGES_FAILURE',

  GET_ALL_POSTS: 'GET_ALL_POSTS',
  GET_ALL_POSTS_SUCCESS: 'GET_ALL_POSTS_SUCCESS',
  GET_ALL_POSTS_FAILURE: 'GET_ALL_POSTS_FAILURE',

  GET_POST_BY_SLUG: 'GET_POST_BY_SLUG',
  GET_POST_BY_SLUG_SUCCESS: 'GET_POST_BY_SLUG_SUCCESS',
  GET_POST_BY_SLUG_FAILURE: 'GET_POST_BY_SLUG_FAILURE'
}
